logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dod?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dahoon@9912

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    mongodb:
      host: localhost
      port: 27017
      database: DoD_Game

    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  elasticsearch:
    uris: http://localhost:9200

rabbitmq:
  exchange:
    game: game.exchange
  queue:
    game:
      save: game.save.queue
  routing:
    game:
      save: game.save